name: Test Build

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build And Upload Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get OpenList Latest Version
        id: op_version
        run: |
          OP_VERSION=$(git ls-remote --tags --sort="v:refname" https://github.com/OpenListTeam/OpenList.git | tail -n1 | sed 's#.*/##')
          if [[ ! $OP_VERSION == v* ]]; then
            echo "Failed To Get OpenList Latest Version" >&2
            exit 1
          fi
          echo "OpenList Latest Version : $OP_VERSION"
          echo "OP_VERSION=$OP_VERSION" >> $GITHUB_OUTPUT

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run ci
        env:
          # PR number + Run ID
          MOE_VERSION: ${{ github.event.pull_request.number || 'manual' }}-${{ github.run_id }}
          OP_VERSION: ${{ steps.op_version.outputs.OP_VERSION }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          # Project name + PR number + Run ID
          name: openlist-moe-${{ github.event.pull_request.number || 'manual' }}-run-${{ github.run_id }}
          path: |
            dist/css/OpenList-Moe.min.css
            dist/js/OpenList-Moe.min.js
          retention-days: 1
